version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es01
    environment:
      - network.host=0.0.0.0
      - network.publish_host=10.128.0.4
      - discovery.zen.ping.unicast.hosts=10.128.0.5
#     - network.host=_site_
      - node.name=es01
      - cluster.name=docker-cluster
        #      - discovery.seed_hosts=10.128.0.5
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://10.128.0.4:9200
      ELASTICSEARCH_HOSTS: '["http://10.128.0.4:9200","http://10.128.0.5:9200"]'
    networks:
      - elastic

        #volumes:
        #  data01:
        #    driver: local
        #  data02:
        #    driver: local
        #  data03:
        #    driver: local

networks:
  elastic:
    driver: bridge
    #        cap_add:
    #            - IPC_LOCK

    #networks:
    #    elasticseach_network:
    #        ipam:
    #            driver: bridge
    #            config:
    #                - subnet: 192.168.144.0/15
    #                - gateway: 10.5.0.1
